### ISSUE TITLE
browserify build process non-functioning

### ISSUE THREAD

**Issue by crowjonah** [tbranyen/scopedcss#7]
Hi there! When I try to build locally after updating to 0.1.1, I get the garbage [version you removed](https://github.com/tbranyen/scopedcss/blob/7271fa523b8c404092f8ef84e0e3723547b5117d/scopedcss.js) in 7271fa5. When I try to use this ScopedCss in the browser, it's claiming to be undefined. Is there any chance I'm missing a dependency?

**Comment by tbranyen** [comment]
I've just patched the package.json main entry to point to the correct dist/scopedcss.js.  Btw it's `ScopedCSS` not `ScopedCss`.
